# Generated by Django 5.0.6 on 2024-06-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование привычки",
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "place",
                    models.TextField(
                        blank=True,
                        help_text="Введите место, в котором необходимо выполнять привычку",
                        null=True,
                        verbose_name="место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку.",
                        null=True,
                        verbose_name="время",
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        help_text="Введите действие, которое представляет собой привычка.",
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="признак приятной привычки"
                    ),
                ),
                ("periodicity", models.IntegerField(default=1)),
                (
                    "time_for_execution",
                    models.IntegerField(
                        default=120, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название вознаграждения")),
            ],
            options={
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
    ]
