# Generated by Django 5.0.6 on 2024-06-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="send_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата отправки"
            ),
        ),
    ]
